### ISSUE TITLE
Timer now not stopping on menu or main menu.

### ISSUE THREAD

**Issue by Vysuals** [DevinR528/bo_autosplitter#2]
Since the autosplitter updated to the new version today, it now doesn't use IGT anymore.

**Comment by DevinR528** [comment]
https://github.com/user-attachments/assets/e560af98-a65f-4c3d-b2c6-dffdc57db972



Is this the behavior that's intended

**Comment by DevinR528** [comment]
Closing as solved by https://github.com/DevinR528/bo_autosplitter/commit/67e0d605aa791df2438019aae40198ee68e284a0
