### ISSUE TITLE
Autosplitter splitting multiple times on file load after save/quit

### ISSUE THREAD

**Issue by MrSir71** [DevinR528/bo_autosplitter#3]
When you load back into your file after a s/q, 4 or 5 splits go off everytime. It is usually a consistent amount in that range in a given run.

I am not sure how this is working now, but one way it could be remedied is by adding ordered autosplits. That way, instead of looking for any of the checked autosplits, it just looks for the next one and hopefully doesn't find it on file load.
|
Maybe the issue can be corrected with the current paradigm but I'm not sure how you are checking the pointers on file load right now.

**Comment by MrSir71** [comment]
Vysuals is having this problem as well

**Comment by DevinR528** [comment]
I fixed this by tracking what splits have been completed and not re-splitting when they are already split. This will not work if LiveSplit has to be restarted (I would consider having to restart LiveSplit a restart to the run also maybe?).

This will be closed via https://github.com/DevinR528/bo_autosplitter/commit/0fbd8a50638e1847ad89363dd4b3063811b66a40 once I have confirmed in discord.

**Comment by MrSir71** [comment]
that sounds like a good solution! I think if livesplit crashes yeah it would be asking a lot to be able to restart it and continue, so no big deal. as long as we can get an IGT for the run the split times don't matter as much. thanks! will test tomorrow

**Comment by DevinR528** [comment]
If this happens again feel free to reopen.
